
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 14;
  public static final int COMA = 10;
  public static final int INTEGER = 5;
  public static final int PROGRAMA = 2;
  public static final int EOF = 0;
  public static final int PUNTCOMA = 9;
  public static final int PARI = 6;
  public static final int ID = 13;
  public static final int IGUAL = 11;
  public static final int error = 1;
  public static final int PROCEDIMIENTO = 3;
  public static final int DOSPUNT = 8;
  public static final int PARD = 7;
  public static final int BEGIN = 12;
  public static final int END = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROGRAMA",
  "PROCEDIMIENTO",
  "END",
  "INTEGER",
  "PARI",
  "PARD",
  "DOSPUNT",
  "PUNTCOMA",
  "COMA",
  "IGUAL",
  "BEGIN",
  "ID",
  "NUM"
  };
}

